name: mimic-fhir
channels:
  - defaults
dependencies:
  - numpy
  - sqlalchemy
  - seaborn
  - pandas
  - psycopg2
  - matplotlib
  - pytest
  - psycopg2
  - jupyter
  - requests
  - json
  - tqdm
  - yapf
  - pip
  - pip:
    - python-dotenv
    
